import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'id' | 'en';

interface Translations {
  [key: string]: {
    id: string;
    en: string;
  };
}

const translations: Translations = {
  // Navigation
  // Navigation
  'nav.home': { id: 'Beranda', en: 'Home' },
  'nav.about': { id: 'Tentang Kami', en: 'About Us' },
  'nav.business': { id: 'Lini Bisnis', en: 'Business Lines' },
  'nav.partners': { id: 'Mitra', en: 'Partners' },
  'nav.certification': { id: 'Sertifikasi', en: 'Certification' },
  'nav.network': { id: 'Jaringan', en: 'Network' },
  'nav.investor': { id: 'Hubungan Investor', en: 'Investor Relations' },
  'nav.news': { id: 'Berita & Media', en: 'News & Media' },
  'nav.career': { id: 'Karir', en: 'Career' },
  'nav.contact': { id: 'Kontak', en: 'Contact' },

  // Hero Section
  'hero.tagline': { id: 'Keunggulan Distribusi Kesehatan Sejak 1968', en: 'Healthcare Distribution Excellence Since 1968' },
  'hero.subtitle': { id: 'Distributor farmasi, alat kesehatan, dan produk consumer health terkemuka di Indonesia dengan jaringan nasional 34 cabang', en: 'Leading pharmaceutical, medical devices, and consumer health distributor in Indonesia with 34 branches nationwide' },
  'hero.cta1': { id: 'Jelajahi Layanan', en: 'Explore Services' },
  'hero.cta2': { id: 'Hubungi Kami', en: 'Contact Us' },

  // Stats
  'stats.years': { id: 'Tahun Pengalaman', en: 'Years of Experience' },
  'stats.branches': { id: 'Cabang Nasional', en: 'National Branches' },
  'stats.partners': { id: 'Mitra Principal', en: 'Principal Partners' },
  'stats.provinces': { id: 'Provinsi Terjangkau', en: 'Provinces Covered' },

  // About
  'about.tagline': { id: 'Profil Perusahaan', en: 'Corporate Profile' },
  'about.title.text': { id: 'Warisan Kepercayaan,', en: 'Legacy of Trust,' },
  'about.title.italic': { id: 'Masa Depan Kesehatan', en: 'Future of Healthcare' },
  'about.description': { id: 'Didirikan pada tahun 1968, PT Penta Valent Tbk telah berkembang menjadi kekuatan distribusi kesehatan nasional yang utama. Kami menjembatani kesenjangan antara produsen global dan masyarakat Indonesia dengan integritas dan keunggulan.', en: 'Founded in 1968, PT Penta Valent Tbk has evolved into a premier national healthcare distribution powerhouse. We bridge the gap between global manufacturers and the Indonesian people with integrity and excellence.' },
  'about.years.impact': { id: 'Tahun Berdampak', en: 'Years of Impact' },
  'about.public.listed': { id: 'Perusahaan Publik', en: 'Publicly Listed' },
  'about.vision.title': { id: 'Visi Kami', en: 'Our Vision' },
  'about.vision.text': { id: 'Menjadi perusahaan distribusi kesehatan terkemuka di Indonesia yang memberikan nilai tambah bagi seluruh pemangku kepentingan.', en: 'To become the leading healthcare distribution company in Indonesia that provides added value for all stakeholders.' },
  'about.mission.title': { id: 'Misi Kami', en: 'Our Mission' },
  'about.mission.text': { id: 'Menyediakan layanan distribusi yang handal, efisien, dan berkualitas tinggi untuk produk farmasi, alat kesehatan, dan consumer health di seluruh Indonesia.', en: 'To provide reliable, efficient, and high-quality distribution services for pharmaceutical, medical devices, and consumer health products throughout Indonesia.' },
  'about.values.tagline': { id: 'Prinsip Dasar', en: 'Foundational Principles' },
  'about.values.title': { id: 'Filosofi Penta Valent', en: 'The Penta Valent Philosophy' },
  'about.timeline.tagline': { id: 'Evolusi Strategis', en: 'Strategic Evolution' },
  'about.timeline.title': { id: 'Dekade Keunggulan', en: 'Decades of Excellence' },

  // Business Lines
  'business.tagline': { id: 'Ekosistem Strategis Kami', en: 'Our Strategic Ecosystem' },
  'business.title.text': { id: 'Mendorong Keunggulan', en: 'Driving Healthcare' },
  'business.title.italic': { id: 'Kesehatan Nasional', en: 'Excellence Nationwide' },
  'business.description': { id: 'Penta Valent menyediakan solusi rantai pasok end-to-end yang terintegrasi, didukung oleh teknologi logistik canggih dan keahlian pasar yang mendalam.', en: 'Penta Valent provides an integrated end-to-end supply chain solution, powered by advanced logistics technology and deep market expertise.' },
  'business.division': { id: 'Divisi Nasional', en: 'National Division' },
  'business.integrity': { id: 'Integritas dalam', en: 'Integrity in' },
  'business.transaction': { id: 'Setiap Transaksi', en: 'Every Transaction' },
  'business.feature.certified': { id: 'Pengiriman Tersertifikasi', en: 'Certified Delivery' },
  'business.advantage.cert.title': { id: 'Sertifikasi', en: 'Certification' },
  'business.advantage.cert.desc': { id: 'Mematuhi standar distribusi global termasuk CDOB & CDAKB.', en: 'Complying with global distribution standards including CDOB & CDAKB.' },
  'business.advantage.innovation.title': { id: 'Inovasi', en: 'Innovation' },
  'business.advantage.innovation.desc': { id: 'Memanfaatkan logistik berbasis AI untuk manajemen inventaris real-time.', en: 'Leveraging AI-driven logistics for real-time inventory management.' },
  'business.advantage.coverage.title': { id: 'Cakupan', en: 'Coverage' },
  'business.advantage.coverage.desc': { id: 'Infrastruktur masif yang membentang di 34 provinsi dengan pengiriman last-mile yang efisien.', en: 'Massive infrastructure spanning 34 provinces with efficient last-mile delivery.' },

  // Partners
  'partners.tagline': { id: 'Aliansi Strategis Kami', en: 'Our Strategic Alliance' },
  'partners.title.text': { id: 'Jaringan Global,', en: 'Global Network,' },
  'partners.title.italic': { id: 'Otoritas Lokal', en: 'Local Authority' },
  'partners.description': { id: 'Kami berkolaborasi dengan produsen kesehatan kelas dunia dan prinsipal lokal untuk menghadirkan produk berkualitas premium di seluruh pasar Indonesia.', en: 'We collaborate with world-class healthcare manufacturers and local principals to deliver premium quality products across the Indonesian market.' },
  'partners.filter.all': { id: 'Semua Mitra', en: 'All Partners' },
  'partners.filter.national': { id: 'Prinsipal Nasional', en: 'National Principals' },
  'partners.filter.global': { id: 'Produsen Global', en: 'Global Manufacturers' },
  'partners.stats.national': { id: 'Prinsipal Nasional', en: 'National Principals' },
  'partners.stats.international': { id: 'Mitra Internasional', en: 'International Partners' },
  'partners.stats.skus': { id: 'SKU Produk Dikelola', en: 'Product SKUs Managed' },
  'partners.cta.tagline': { id: 'Bangun Masa Depan Bersama Kami', en: 'Build the Future with Us' },
  'partners.cta.title.text': { id: 'Tingkatkan Distribusi Anda', en: 'Elevate Your Distribution' },
  'partners.cta.title.accent': { id: 'Jangkauan Nasional', en: 'Reach Nationwide' },
  'partners.cta.description': { id: 'Terhubung dengan infrastruktur distribusi kesehatan terbesar di Indonesia. Tim kami siap mengembangkan bisnis Anda di seluruh nusantara.', en: 'Connect with the largest healthcare distribution infrastructure in Indonesia. Our team is ready to scale your business across the archipelago.' },
  'partners.cta.button': { id: 'Menjadi Mitra', en: 'Become a Partner' },

  // Network
  'network.tagline': { id: 'Jejak Nasional', en: 'National Footprint' },
  'network.title.text': { id: 'Cakupan Total', en: 'Total Archipelago' },
  'network.title.italic': { id: 'Nusantara', en: 'Coverage' },
  'network.description': { id: 'Jaringan distribusi kami yang luas memastikan produk kesehatan berkualitas tinggi menjangkau setiap sudut Indonesia dengan efisiensi dan integritas.', en: 'Our expansive distribution network ensures that high-quality healthcare products reach every corner of Indonesia with efficiency and integrity.' },
  'network.stats.main': { id: 'Cabang Utama', en: 'Main Branches' },
  'network.stats.depots': { id: 'Depo Distribusi', en: 'Distribution Depots' },
  'network.stats.provinces': { id: 'Provinsi', en: 'Provinces' },
  'network.intel.title': { id: 'Kecerdasan', en: 'Network' },
  'network.intel.italic': { id: 'Jaringan', en: 'Intelligence' },
  'network.intel.live': { id: 'Operasi Regional Langsung', en: 'Live Regional Operations' },
  'network.legend.hq': { id: 'Kantor Pusat', en: 'Headquarters' },
  'network.legend.branch': { id: 'Cabang Regional', en: 'Regional Branch' },
  'network.legend.depot': { id: 'Depo Logistik', en: 'Logistic Depot' },
  'network.explore.title': { id: 'Jelajahi Jaringan Kami', en: 'Explore Our Network' },
  'network.explore.tagline': { id: 'Direktori Regional', en: 'Regional Directory' },
  'network.filter.all': { id: 'Semua Provinsi', en: 'All Provinces' },
  'network.locations': { id: 'Lokasi', en: 'Locations' },
  'network.view': { id: 'Lihat', en: 'View' },

  // Investor
  'investor.tagline': { id: 'Hubungan Investor', en: 'Investor Relations' },
  'investor.title.text': { id: 'Transparansi &', en: 'Transparency &' },
  'investor.title.italic': { id: 'Pertumbuhan Berkelanjutan', en: 'Sustainable Growth' },
  'investor.description': { id: 'Sebagai perusahaan terbuka, kami berkomitmen untuk menjaga standar tata kelola perusahaan tertinggi dan memberikan nilai jangka panjang kepada pemegang saham kami.', en: 'As a publicly listed company, we are committed to maintaining the highest standards of corporate governance and delivering long-term value to our shareholders.' },
  'investor.ticker.label': { id: 'Simbol Saham BEI', en: 'IDX Stock Symbol' },
  'investor.stats.revenue': { id: 'Pertumbuhan Pendapatan', en: 'Revenue Growth' },
  'investor.stats.mcap': { id: 'Kapitalisasi Pasar', en: 'Market Capitalization' },
  'investor.stats.dividen': { id: 'Yield Dividen', en: 'Dividen Yield' },
  'investor.stats.growth': { id: 'Pertumbuhan 2025', en: 'Growth 2025' },
  'investor.reports.title': { id: 'Laporan Keuangan', en: 'Financial Reports' },
  'investor.reports.desc': { id: 'Akses laporan tahunan terbaru, pengajuan kuartalan, dan presentasi investor kami.', en: 'Access our latest annual reports, quarterly filings, and investor presentations.' },
  'investor.calendar.title': { id: 'Kalender Investor', en: 'Investor Calendar' },
  'investor.calendar.upcoming': { id: 'Acara Mendatang', en: 'Upcoming Event' },
  'investor.disclosure.share': { id: 'Bagikan Pengungkapan', en: 'Share Disclosure' },
  'investor.nav.title': { id: 'Navigasi Investor', en: 'Investor Navigation' },
  'investor.nav.highlights': { id: 'Ringkasan Investor', en: 'Investor Highlight' },
  'investor.nav.stock': { id: 'Informasi Saham', en: 'Stock Information' },
  'investor.nav.financials': { id: 'Laporan Keuangan', en: 'Financial Reports' },
  'investor.nav.prospectus': { id: 'Prospektus', en: 'Prospectus' },
  'investor.nav.rups': { id: 'RUPS', en: 'General Meetings' },
  'investor.nav.disclosure': { id: 'Keterbukaan Informasi', en: 'Information Disclosure' },
  'investor.docs.empty': { id: 'Belum ada dokumen yang tersedia di kategori ini.', en: 'No documents available for this category yet.' },
  'investor.docs.download': { id: 'Unduh PDF', en: 'Download PDF' },
  'investor.stock.performance': { id: 'Performa Saham PEVE', en: 'PEVE Stock Performance' },
  'investor.stock.chart_placeholder': { id: 'Visualisasi Grafik Saham - Hub Realtime', en: 'Stock Chart Visualization - Realtime Hub' },
  'investor.contact.title': { id: 'Hubungi IR', en: 'Contact IR' },
  'investor.contact.desc': { id: 'Ada pertanyaan mengenai performa perusahaan?', en: 'Have questions regarding company performance?' },
  'investor.contact.button': { id: 'Email Tim IR', en: 'Email IR Team' },

  // News
  'news.tagline': { id: 'Pers & Wawasan', en: 'Press & Insights' },
  'news.title.text': { id: 'Kecerdasan', en: 'Corporate' },
  'news.title.italic': { id: 'Korporat', en: 'Intelligence' },
  'news.description': { id: 'Tetap terupdate dengan ekspansi operasional terbaru kami, tonggak keuangan, dan kemitraan strategis saat kami memimpin sektor distribusi kesehatan.', en: 'Stay updated with our latest operational expansions, financial milestones, and strategic partnerships as we lead the healthcare distribution sector.' },
  'news.archive': { id: 'Penemuan Arsip', en: 'Archive Discovery' },
  'news.discovery': { id: 'Arsip Penemuan', en: 'Discovery Archive' },
  'news.readmore': { id: 'Baca Selengkapnya', en: 'Read Disclosure' },
  'news.cta': { id: 'Lihat Semua Berita', en: 'View All News' },
  'news.source': { id: 'Sumber Internal', en: 'Source Internal' },
  'news.comm': { id: 'Komunikasi Korporat', en: 'Corporate Communications' },
  'news.share': { id: 'Bagikan Pengungkapan', en: 'Share Disclosure' },
  'news.cat.award': { id: 'Penghargaan', en: 'Award' },
  'news.cat.expansion': { id: 'Ekspansi', en: 'Expansion' },
  'news.cat.investor': { id: 'Investor', en: 'Investor' },
  'news.cat.partnership': { id: 'Kemitraan', en: 'Partnership' },
  'news.cat.press_release': { id: 'Rilis Pers', en: 'Press Release' },
  'news.cat.corporate': { id: 'Korporat', en: 'Corporate' },

  // Career
  'career.title': { id: 'Karir di PEVE', en: 'Career at PEVE' },
  'career.subtitle': { id: 'Bergabunglah dengan tim kami dan kembangkan karir Anda', en: 'Join our team and develop your career' },
  'career.apply': { id: 'Lamar Sekarang', en: 'Apply Now' },
  'career.cta': { id: 'Lihat Lowongan', en: 'Explore Openings' },
  'career.hiring': { id: 'Kami Merekrut Sekarang', en: 'We Are Hiring Now' },
  'career.opportunity': { id: 'Peluang Masa Depan', en: 'Future Opportunities' },
  'career.excellence': { id: 'Mengejar Keunggulan', en: 'Pursuing Excellence' },
  'career.filter.all': { id: 'Semua Bidang', en: 'All Fields' },
  'career.filter.operation': { id: 'Operasi', en: 'Operation' },
  'career.filter.commercial': { id: 'Komersial', en: 'Commercial' },
  'career.filter.support': { id: 'Pendukung', en: 'Support' },
  'career.detail': { id: 'Detail', en: 'Detail' },
  'career.apply_now': { id: 'Lamar Sekarang', en: 'Apply Now' },
  'career.no_positions': { id: 'Belum ada posisi tersedia', en: 'No positions available' },
  'career.check_back': { id: 'Silakan cek kembali di waktu mendatang.', en: 'Please check back in the future.' },
  'career.talent_scout.title': { id: 'Talent Scout', en: 'Talent Scout' },
  'career.talent_scout.desc': { id: 'Tidak menemukan posisi yang cocok? Kirim resume anda ke bank talenta kami.', en: 'Didn\'t find a matching position? Submit your resume to our talent bank.' },
  'career.talent_scout.button': { id: 'Submit CV General', en: 'Submit CV General' },
  'career.filter.title': { id: 'Filter Bidang', en: 'Filter Occupation' },
  'career.modal.position_details': { id: 'Detail Posisi', en: 'Position Details' },
  'career.modal.description': { id: 'Deskripsi', en: 'Description' },
  'career.modal.requirements': { id: 'Persyaratan', en: 'Requirements' },
  'career.modal.continue': { id: 'Lanjutkan Pendaftaran', en: 'Continue Application' },
  'career.form.title': { id: 'Kirim Lamaran', en: 'Submit Application' },
  'career.form.subtitle': { id: 'Mendaftarkan posisi untuk', en: 'Applying for position' },
  'career.form.name': { id: 'Nama Lengkap', en: 'Full Name' },
  'career.form.email': { id: 'Email Applicant', en: 'Applicant Email' },
  'career.form.phone': { id: 'Nomor Telepon', en: 'Phone Number' },
  'career.form.cover_letter': { id: 'Cover Letter / Pesan Singkat', en: 'Cover Letter / Short Message' },
  'career.form.submitting': { id: 'Sedang Mengirim...', en: 'Submitting...' },
  'career.form.success_title': { id: 'Aplikasi Terkirim!', en: 'Application Sent!' },
  'career.form.success_desc': { id: 'Tim talent kami akan mereview profil anda segera.', en: 'Our talent team will review your profile shortly.' },
  'career.form.verification': { id: 'Verifikasi Manusia', en: 'Human Verification' },
  'career.form.general_app': { id: 'Aplikasi Umum', en: 'General Application' },

  // Contact
  'contact.tagline': { id: 'Tetap Terhubung', en: 'Stay Connected' },
  'contact.title.text': { id: 'Kemitraan Mulai', en: 'Partnership Starts' },
  'contact.title.italic': { id: 'Di Sini', en: 'Right Here' },
  'contact.description': { id: 'Hubungi tim eksekutif kami untuk mendiskusikan peluang distribusi nasional atau pertanyaan korporat lainnya.', en: 'Contact our executive team to discuss national distribution opportunities or other corporate inquiries.' },
  'contact.info.title': { id: 'Saluran Direksi', en: 'Direct Channels' },
  'contact.info.desc': { id: 'Tim kami menanggapi setiap pertanyaan korporat dalam waktu 24 jam kerja.', en: 'Our team responds to every corporate inquiry within 24 business hours.' },
  'contact.phone.label': { id: 'Hubungi Kami', en: 'Call Us' },
  'contact.email.label': { id: 'Email Kami', en: 'Email Us' },
  'contact.address.label': { id: 'Kantor Pusat', en: 'Headquarters' },
  'contact.social.label': { id: 'Ikuti Kami', en: 'Follow Us' },
  'contact.form.identity': { id: 'Identitas Pengirim', en: 'Sender Identity' },
  'contact.form.name_placeholder': { id: 'Nama Lengkap', en: 'Full Name' },
  'contact.form.corporate_email': { id: 'Email', en: 'Email' },
  'contact.form.email_placeholder': { id: 'email@perusahaan.com', en: 'email@company.com' },
  'contact.form.phone_label': { id: 'Nomor Komunikasi', en: 'Communication Number' },
  'contact.form.phone_placeholder': { id: '+62 ...', en: '+62 ...' },
  'contact.form.consultation_type': { id: 'Jenis Konsultasi', en: 'Consultation Type' },
  'contact.form.category_placeholder': { id: 'Pilih Kategori', en: 'Select Category' },
  'contact.form.business': { id: 'Business Enquiry', en: 'Business Enquiry' },
  'contact.form.employment': { id: 'Employment Enquiry', en: 'Employment Enquiry' },
  'contact.form.media': { id: 'Media Enquiry', en: 'Media Enquiry' },
  'contact.form.order': { id: 'Order Enquiry', en: 'Order Enquiry' },
  'contact.form.complain': { id: 'Product Complain', en: 'Product Complain' },
  'contact.form.return': { id: 'Product Return', en: 'Product Return' },
  'contact.form.intelligence': { id: 'Detail Intelligence', en: 'Intelligence Details' },
  'contact.form.message_placeholder': { id: 'Bagaimana kami dapat mendukung visi anda?', en: 'How can we support your vision?' },
  'contact.form.bot_protection': { id: 'Bot Protection', en: 'Bot Protection' },
  'contact.form.submit': { id: 'Kirim Intelligence Report', en: 'Send Intelligence Report' },
  'contact.form.submitting': { id: 'Transmitting Data...', en: 'Transmitting Data...' },
  'contact.sidebar.hq': { id: 'Kantor Pusat', en: 'Headquarters' },
  'contact.sidebar.hotline': { id: 'Hotline Korporat', en: 'Corporate Hotline' },
  'contact.sidebar.correspondence': { id: 'Korespondensi', en: 'Correspondence' },
  'contact.sidebar.operational': { id: 'Operasional', en: 'Operational' },
  'contact.sidebar.whatsapp': { id: 'Chat di WhatsApp', en: 'Chat on WhatsApp' },
  'contact.success.title': { id: 'Transmission Success', en: 'Transmission Success' },
  'contact.success.msg': { id: 'Pesan Anda telah kami terima.', en: 'Your inquiry has been logged successfully.' },
  'contact.hours.label': { id: 'Jam Operasional', en: 'Operating Hours' },
  'contact.hours.value': { id: 'Senin - Jumat: 08:30 - 17:00 WIB', en: 'Mon - Fri: 08:30 - 17:00 WIB' },

  // Footer
  'footer.about': { id: 'Tentang PEVE', en: 'About PEVE' },
  'footer.description': { id: 'Didirikan pada tahun 1968, PT Penta Valent Tbk adalah distributor farmasi, alat kesehatan, dan produk konsumen terpercaya di Indonesia.', en: 'Founded in 1968, PT Penta Valent Tbk is a trusted distributor of pharmaceuticals, medical devices, and consumer products in Indonesia.' },
  'footer.quicklinks': { id: 'Tautan Cepat', en: 'Quick Links' },
  'footer.services': { id: 'Layanan', en: 'Services' },
  'footer.contact': { id: 'Kontak', en: 'Contact' },
  'footer.copyright': { id: 'Hak Cipta', en: 'Copyright' },
  'footer.privacy': { id: 'Kebijakan Privasi', en: 'Privacy Policy' },
  'footer.faq': { id: 'Tanya Jawab (FAQ)', en: 'F.A.Q' },
  'footer.terms': { id: 'Syarat & Ketentuan', en: 'Terms & Conditions' },
  'footer.rights': { id: 'Seluruh hak cipta dilindungi.', en: 'All rights reserved.' },
  'footer.column.contact': { id: 'Hubungi Kami', en: 'Contact Us' },
  'footer.column.corporate': { id: 'Korporat', en: 'Corporate' },
  'footer.column.stakeholders': { id: 'Pemangku Kepentingan', en: 'Stakeholders' },
  'footer.contact.hq': { id: 'Kantor Pusat Jakarta', en: 'Jakarta HQ' },
  'footer.contact.digital': { id: 'Surat Digital', en: 'Digital Mail' },
  'footer.contact.ho': { id: 'Kantor Pusat', en: 'Head Office' },
  'footer.contact.hours': { id: 'Jam Operasional', en: 'Business Hours' },
  'footer.contact.days': { id: 'Senin - Jumat: 08:00 - 17:00', en: 'Mon - Fri: 08:00 - 17:00' },
  'footer.code_conduct': { id: 'Kode Etik', en: 'Code of Conduct' },

  // Cookie
  'cookie.message': { id: 'Website ini menggunakan cookies untuk memastikan Anda mendapatkan pengalaman terbaik di website kami.', en: 'This website uses cookies to ensure you get the best experience on our website.' },
  'cookie.accept': { id: 'Terima', en: 'Accept' },
  'cookie.manage': { id: 'Kelola Preferensi', en: 'Manage Preferences' },
  'cookie.policy': { id: 'Kebijakan Cookie', en: 'Cookie Policy' },
  'cookie.save': { id: 'Simpan Konfigurasi', en: 'Save Configuration' },
  'cookie.pref.necessary': { id: 'Wajib', en: 'Necessary' },
  'cookie.pref.analytics': { id: 'Analitik', en: 'Analytics' },
  'cookie.pref.marketing': { id: 'Pemasaran', en: 'Marketing' },
  'cookie.pref.title': { id: 'Preferensi', en: 'Preferences' },
  'cookie.pref.subtitle': { id: 'Konfigurasi Node', en: 'Configuration Node' },

  // Admin & Login
  'login.title': { id: 'Panel Admin', en: 'Admin Panel' },
  'login.subtitle': { id: 'Masuk untuk mengelola website Anda', en: 'Sign in to manage your website' },
  'login.email': { id: 'Alamat Email', en: 'Email Address' },
  'login.password': { id: 'Kata Sandi', en: 'Password' },
  'login.remember': { id: 'Ingat saya', en: 'Remember me' },
  'login.forgot': { id: 'Lupa kata sandi?', en: 'Forgot password?' },
  'login.button': { id: 'Masuk Ke Panel', en: 'Sign In to Panel' },
  'login.signing': { id: 'Sedang Masuk...', en: 'Signing in...' },
  'login.back': { id: 'Kembali ke Website', en: 'Back to Website' },
  'login.footer': { id: 'Hak Cipta © 2025 PT Penta Valent Tbk.', en: 'Copyright © 2025 PT Penta Valent Tbk.' },
  'login.credentials.title': { id: 'Kredensial Demo:', en: 'Demo Credentials:' },
  'admin.dashboard': { id: 'Dasbor', en: 'Dashboard' },
  'admin.news': { id: 'Kelola Berita', en: 'News Manager' },
  'admin.branches': { id: 'Cabang & Jaringan', en: 'Branches & Network' },
  'admin.messages': { id: 'Pesan Masuk', en: 'Incoming Messages' },
  'admin.logout': { id: 'Keluar', en: 'Logout' },
  'admin.profile': { id: 'Profil', en: 'Profile' },
  'admin.settings': { id: 'Pengaturan', en: 'Settings' },

  'admin.menu.dashboard': { id: 'Dasbor', en: 'Dashboard' },
  'admin.menu.hero': { id: 'Slider Banner', en: 'Banner Slider' },
  'admin.menu.menus': { id: 'Pengelola Menu', en: 'Menu Manager' },
  'admin.menu.company': { id: 'Profil Perusahaan', en: 'Company Profile' },
  'admin.menu.news': { id: 'Berita & Media', en: 'News & Media' },
  'admin.menu.careers': { id: 'Karir', en: 'Careers' },
  'admin.menu.investor': { id: 'Investor', en: 'Investor' },
  'admin.menu.website': { id: 'Pengaturan Website', en: 'Website Settings' },
  'admin.menu.recruitment': { id: 'Rekrutmen', en: 'Recruitment' },
  'admin.menu.content': { id: 'Konten Website', en: 'Website Content' },
  'admin.menu.calendar': { id: 'Kalender Investor', en: 'Investor Calendar' },
  'admin.menu.messages': { id: 'Pesan Masuk', en: 'Messages' },
  'admin.menu.applications': { id: 'Lamaran Pekerjaan', en: 'Job Applications' },
  'admin.menu.channels': { id: 'Pengaturan Saluran', en: 'Channel Settings' },
  'admin.menu.faqs': { id: 'Pengelola FAQ', en: 'FAQ Manager' },
  'admin.menu.users': { id: 'Manajemen Pengguna', en: 'User Management' },
  'admin.menu.analytics': { id: 'Analitik Trafik', en: 'Traffic Analytics' },
  'admin.menu.seo': { id: 'Pengaturan SEO', en: 'SEO Settings' },
  'admin.menu.legal': { id: 'Dokumen Hukum', en: 'Legal Documents' },
  'admin.menu.newsletter': { id: 'Buletin', en: 'Newsletter' },
  'admin.menu.settings': { id: 'Pengaturan Situs', en: 'Site Settings' },
  'admin.menu.db_backup': { id: 'Backup Database', en: 'Database Backup' },
  'admin.menu.profile': { id: 'Profil Saya', en: 'My Profile' },
  'admin.menu.security': { id: 'Keamanan & Privasi', en: 'Security & Privacy' },
  'admin.menu.signout': { id: 'Keluar', en: 'Sign Out' },
  'admin.menu.change_password': { id: 'Ganti Kata Sandi', en: 'Change Password' },
  'admin.menu.activity_logs': { id: 'Log Aktivitas', en: 'Activity Logs' },
  'admin.menu.security_logs': { id: 'Log Keamanan', en: 'Security Logs' },

  // Admin Branch Manager
  'admin.branch.title': { id: 'Jaringan Cabang', en: 'Branch Network' },
  'admin.branch.subtitle': { id: 'Kelola titik distribusi global dan kantor pusat logistik', en: 'Manage global distribution nodes and logistical headquarters' },
  'admin.branch.add': { id: 'Tambah Node', en: 'Add Node' },
  'admin.branch.stats.nodes': { id: 'Node Global', en: 'Global Nodes' },
  'admin.branch.stats.hq': { id: 'Kantor Pusat', en: 'Headquarters' },
  'admin.branch.stats.active': { id: 'Cabang Aktif', en: 'Active Branches' },
  'admin.branch.stats.depots': { id: 'Depo Regional', en: 'Regional Depots' },
  'admin.branch.stats.distribution_points': { id: 'Titik Distribusi', en: 'Distribution Points' },
  'admin.branch.search_placeholder': { id: 'Cari dalam grid global (Nama, Kota, Provinsi)...', en: 'Search within the global grid (Name, City, Province)...' },
  'admin.branch.filter.universal': { id: 'Universal', en: 'Universal' },
  'admin.branch.filter.hq': { id: 'Unit Pusat', en: 'HQ Units' },
  'admin.branch.filter.branches': { id: 'Cabang', en: 'Branches' },
  'admin.branch.filter.depots': { id: 'Depo', en: 'Depots' },
  'admin.branch.table.sequence': { id: 'Urutan', en: 'Sequence' },
  'admin.branch.table.identity': { id: 'Identitas Node', en: 'Node Identity' },
  'admin.branch.table.type': { id: 'Protokol / Tipe', en: 'Protocol / Type' },
  'admin.branch.table.position': { id: 'Posisi Spasial', en: 'Spatial Position' },
  'admin.branch.table.status': { id: 'Status', en: 'Status' },
  'admin.branch.table.actions': { id: 'Aksi', en: 'Actions' },
  'admin.branch.loading': { id: 'Sinkronisasi Ledger Jaringan...', en: 'Syncing Network Ledger...' },
  'admin.branch.empty': { id: 'Tidak ada sinyal ditemukan di sektor ini', en: 'No signals found in this sector' },
  'admin.branch.status.active': { id: 'BERDENYUT', en: 'PULSING' },
  'admin.branch.status.inactive': { id: 'DIAM', en: 'SILENT' },
  'admin.branch.modal.edit': { id: 'Rekalibrasi Node', en: 'Recalibrate Node' },
  'admin.branch.modal.add': { id: 'Inisialisasi Node', en: 'Initialize Node' },
  'admin.branch.modal.terminal': { id: 'Terminal Geometri Distribusi', en: 'Distribution Geometry Terminal' },
  'admin.branch.form.name': { id: 'Nama Protokol', en: 'Protocol Name' },
  'admin.branch.form.type': { id: 'Klasifikasi Fasilitas', en: 'Facility Classification' },
  'admin.branch.form.city': { id: 'Sektor / Kota', en: 'Sector / City' },
  'admin.branch.form.province': { id: 'Wilayah / Provinsi', en: 'Region / Province' },
  'admin.branch.form.address': { id: 'Landmark Fisik / Alamat', en: 'Physical Landmark / Address' },
  'admin.branch.form.phone': { id: 'Komunikasi / Telepon', en: 'Comms / Phone' },
  'admin.branch.form.email': { id: 'Uplink Digital / Email', en: 'Digital Uplink / Email' },
  'admin.branch.form.geo': { id: 'Lokalisasi Geografis', en: 'Geographic Localization' },
  'admin.branch.form.map_link': { id: 'Tautan Google Maps', en: 'Google Map Link' },
  'admin.branch.form.coords_extracted': { id: 'Koordinat Diekstrak', en: 'Coordinates Extracted' },
  'admin.branch.form.lat': { id: 'Latitudo Terdeteksi', en: 'Detected Latitude' },
  'admin.branch.form.lng': { id: 'Longitudo Terdeteksi', en: 'Detected Longitude' },
  'admin.branch.form.status': { id: 'Status Denyut', en: 'Pulsing Status' },
  'admin.branch.form.active_desc': { id: 'TRANSMISI AKTIF', en: 'ACTIVE TRANSMISSION' },
  'admin.branch.form.standby_desc': { id: 'MODE STANDBY', en: 'STANDBY MODE' },
  'admin.branch.form.discard': { id: 'Buang', en: 'Discard' },
  'admin.branch.form.update_btn': { id: 'KONFIRMASI PEMBARUAN', en: 'CONFIRM UPDATE' },
  'admin.branch.form.deploy_btn': { id: 'LUNCURKAN NODE', en: 'DEPLOY NODE' },

  // Admin Career Manager
  'admin.career.search_placeholder': { id: 'Cari peluang...', en: 'Search opportunities...' },
  'admin.career.loading': { id: 'Memindai Jaringan Karir...', en: 'Scanning Career Network...' },
  'admin.career.empty_title': { id: 'Tidak Ada Lowongan Global', en: 'No Global Vacancies' },
  'admin.career.empty_desc': { id: 'Mulai bangun tim Anda dengan memposting lowongan pekerjaan pertama.', en: 'Start building your team by posting the first job opening.' },
  'admin.career.empty_search': { id: 'Tidak ada hasil yang cocok.', en: 'No matches found.' },
  'admin.career.modal.add_title': { id: 'Luncurkan Lowongan Baru', en: 'Launch New Opening' },
  'admin.career.modal.edit_title': { id: 'Perbarui Peluang', en: 'Update Opportunity' },
  'admin.career.modal.subtitle': { id: 'Akuisisi Bakat Global', en: 'Global Talent Acquisition' },
  'admin.career.form.title': { id: 'Judul Pekerjaan', en: 'Job Title' },
  'admin.career.form.dept': { id: 'Departemen', en: 'Department' },
  'admin.career.form.location': { id: 'Lokasi Kantor', en: 'Office Location' },
  'admin.career.form.type': { id: 'Model Pekerjaan', en: 'Employment Model' },
  'admin.career.form.deadline': { id: 'Tanggal Penutupan', en: 'Closing Date' },
  'admin.career.form.mission_title': { id: 'Misi Operasional (Deskripsi)', en: 'Operational Mission (Description)' },
  'admin.career.form.desc_id': { id: 'Deskripsi (Bahasa Indonesia)', en: 'Description (Bahasa Indonesia)' },
  'admin.career.form.desc_en': { id: 'Deskripsi (English)', en: 'Description (English)' },
  'admin.career.form.desc_placeholder_id': { id: 'Tuliskan deskripsi pekerjaan...', en: 'Write job description...' },
  'admin.career.form.desc_placeholder_en': { id: 'Write global job description...', en: 'Write global job description...' },
  'admin.career.form.req_title': { id: 'Persyaratan Taktis', en: 'Tactical Requirements' },
  'admin.career.form.req_id': { id: 'Persyaratan (Bahasa Indonesia)', en: 'Requirements (Bahasa Indonesia)' },
  'admin.career.form.req_en': { id: 'Persyaratan (English)', en: 'Requirements (English)' },
  'admin.career.form.req_placeholder_id': { id: 'Tuliskan kriteria pelamar...', en: 'Write applicant criteria...' },
  'admin.career.form.req_placeholder_en': { id: 'Write global applicant criteria...', en: 'Write global applicant criteria...' },
  'admin.career.form.status_title': { id: 'Status Penerbitan', en: 'Publishing Status' },
  'admin.career.form.status_active': { id: 'Terlihat oleh pelamar global', en: 'Visible to global applicants' },
  'admin.career.form.status_draft': { id: 'Draf internal pribadi', en: 'Private internal draft' },
  'admin.career.form.discard': { id: 'Buang Perubahan', en: 'Discard Changes' },
  'admin.career.form.close_preview': { id: 'Tutup Pratinjau', en: 'Close Preview' },
  'admin.career.form.submit_update': { id: 'KIRIM MISI TERPENUHI', en: 'SUBMIT UPGRADED MISSION' },
  'admin.career.form.submit_launch': { id: 'LUNCURKAN LOWONGAN GLOBAL', en: 'LAUNCH GLOBAL VACANCY' },
  'admin.career.global_sync': { id: 'Sinkronisasi Global', en: 'Global Sync' },

  // Admin FAQ Manager
  'admin.faq.title': { id: 'Pengelola FAQ', en: 'FAQ Manager' },
  'admin.faq.subtitle': { id: 'Kelola pertanyaan dan jawaban yang sering diajukan', en: 'Manage frequently asked questions and answers' },
  'admin.faq.add': { id: 'Tambah FAQ Baru', en: 'Add New FAQ' },
  'admin.faq.search_placeholder': { id: 'Cari pertanyaan...', en: 'Search questions...' },
  'admin.faq.loading': { id: 'Memuat FAQ...', en: 'Loading FAQs...' },
  'admin.faq.empty_title': { id: 'Tidak ada FAQ ditemukan', en: 'No FAQs found' },
  'admin.faq.empty_desc': { id: 'Mulai dengan menambahkan pertanyaan umum untuk membantu pengguna Anda', en: 'Start by adding common questions to help your users' },
  'admin.faq.modal.add_title': { id: 'Tambah Pertanyaan', en: 'Add Question' },
  'admin.faq.modal.edit_title': { id: 'Ubah Pertanyaan', en: 'Edit Question' },
  'admin.faq.modal.subtitle': { id: 'Buat entri FAQ yang komprehensif', en: 'Create a comprehensive FAQ entry' },
  'admin.faq.form.category': { id: 'Kategori', en: 'Category' },
  'admin.faq.form.sort': { id: 'Urutan', en: 'Sort Order' },
  'admin.faq.form.question_id': { id: 'Pertanyaan (ID)', en: 'Question (ID)' },
  'admin.faq.form.question_en': { id: 'Pertanyaan (EN)', en: 'Question (EN)' },
  'admin.faq.form.answer_id': { id: 'Jawaban (ID)', en: 'Answer (ID)' },
  'admin.faq.form.answer_en': { id: 'Jawaban (EN)', en: 'Answer (EN)' },
  'admin.faq.form.publish': { id: 'Terbitkan Segera', en: 'Publish Immediately' },
  'admin.faq.form.save': { id: 'Simpan Perubahan', en: 'Save Changes' },
  'admin.faq.form.publish_btn': { id: 'Terbitkan FAQ', en: 'Publish FAQ' },
  'admin.faq.cat.general': { id: 'Informasi Umum', en: 'General Information' },
  'admin.faq.cat.business': { id: 'Bisnis & Layanan', en: 'Business & Services' },
  'admin.faq.cat.investor': { id: 'Hubungan Investor', en: 'Investor Relations' },
  'admin.faq.cat.career': { id: 'Karir', en: 'Careers' },
  'admin.faq.cat.other': { id: 'Lainnya', en: 'Other/Misc' },

  // Admin Applications Manager
  'admin.applications.search_placeholder': { id: 'Cari Kandidat...', en: 'Find Candidate...' },
  'admin.applications.filter.status': { id: 'Status Global', en: 'Global Status' },
  'admin.applications.loading': { id: 'Memindai Kolam Bakat...', en: 'Scanning Talent Pool...' },
  'admin.applications.empty_title': { id: 'Tidak Ada Kecocokan Global', en: 'No Global Match' },
  'admin.applications.empty_desc': { id: 'Sistem akuisisi bakat global tidak menunjukkan catatan yang cocok dengan urutan Anda saat ini.', en: 'Global talent acquisition systems show no records matching your current sequence.' },
  'admin.applications.export': { id: 'Ekspor Kandidat', en: 'Export Candidates' },
  'admin.applications.table.contact': { id: 'Kontak Langsung', en: 'Direct Contact' },
  'admin.applications.table.protocol': { id: 'Protokol Akses', en: 'Access Protocol' },
  'admin.applications.table.transmission': { id: 'Tanggal Transmisi', en: 'Transmission Date' },
  'admin.applications.table.mission': { id: 'Pernyataan Misi / Surat Lamaran', en: 'Mission Statement / Cover Letter' },
  'admin.applications.table.files': { id: 'BERKAS BAKAT', en: 'TALENT FILES' },
  'admin.applications.table.resume_view': { id: 'Lihat Resume', en: 'View Resume' },
  'admin.applications.table.no_resume': { id: 'TIDAK ADA RESUME VISUAL', en: 'NO VISUAL RESUME' },
  'admin.applications.table.decision': { id: 'KONSOL KEPUTUSAN', en: 'DECISION CONSOLE' },
  'admin.applications.status.pending': { id: 'Tertunda', en: 'Pending' },
  'admin.applications.status.reviewed': { id: 'Sedang Ditinjau', en: 'Under Review' },
  'admin.applications.status.accepted': { id: 'Diterima', en: 'Accepted' },
  'admin.applications.status.rejected': { id: 'Ditolak', en: 'Rejected' },
  'admin.applications.action.review': { id: 'Meninjau', en: 'Reviewing' },
  'admin.applications.action.accept': { id: 'Terima', en: 'Accept' },
  'admin.applications.action.reject': { id: 'Tolak', en: 'Reject' },
  'admin.applications.action.waitlist': { id: 'Daftar Tunggu', en: 'Waitlist' },

  // Admin Recruitment Hub
  'admin.recruitment.title': { id: 'Pusat Rekrutmen', en: 'Recruitment Hub' },
  'admin.recruitment.subtitle': { id: 'Kelola posisi lowongan dan lamaran', en: 'Manage opening positions and applications' },
  'admin.recruitment.tab.careers': { id: 'Karir', en: 'Careers' },
  'admin.recruitment.tab.applications': { id: 'Lamaran Pekerjaan', en: 'Job Applications' },

  // Admin Messages Manager
  'admin.messages.title': { id: 'Kotak Masuk', en: 'Inquiry Inbox' },
  'admin.messages.subtitle_unread': { id: 'Ada {count} pesan baru yang menunggu respon', en: 'There are {count} new signals awaiting response' },
  'admin.messages.subtitle_all_read': { id: 'Semua transmisi telah ditinjau', en: 'All transmissions have been reviewed' },
  'admin.messages.export_excel': { id: 'Ekspor ke Excel', en: 'Export Inbox to Excel' },
  'admin.messages.search_placeholder': { id: 'Cari pesan...', en: 'Search inbox...' },
  'admin.messages.filter.all': { id: 'Semua', en: 'Universal' },
  'admin.messages.filter.unread': { id: 'Belum Dibaca', en: 'Unread' },
  'admin.messages.filter.read': { id: 'Sudah Dibaca', en: 'Read' },
  'admin.messages.empty': { id: 'Kotak masuk kosong di frekuensi ini', en: 'Inbox is silent on this frequency' },
  'admin.messages.select_prompt': { id: 'Pilih pesan untuk ditinjau', en: 'Select signal to review' },
  'admin.messages.select_desc': { id: 'Pilih pertanyaan dari daftar untuk mulai meninjau dan merespon.', en: 'Choose an inquiry from the list to start reviewing and responding.' },
  'admin.messages.reply_btn': { id: 'Balas via Email Resmi', en: 'Reply via Official Email' },
  'admin.messages.delete_success': { id: 'Pesan berhasil dihapus', en: 'Message deleted permanently' },
  'admin.messages.delete_error': { id: 'Gagal menghapus pesan', en: 'Failed to delete message' },
  'admin.messages.no_subject': { id: 'Tanpa Subjek', en: 'No Subject' },
  'admin.messages.consultation_general': { id: 'Umum', en: 'General' },

  // Admin Dashboard
  'admin.dashboard.system_overview': { id: 'Ikhtisar Sistem', en: 'System Overview' },
  'admin.dashboard.welcome': { id: 'Selamat Datang Kembali', en: 'Welcome Back' },
  'admin.dashboard.subtitle': { id: 'Pantau kinerja operasional dan metrik rekrutmen Anda dari pusat komando ini.', en: 'Monitor your operational performance and recruitment metrics from this command center.' },
  'admin.dashboard.recent_messages': { id: 'Pesan Terbaru', en: 'Recent Signals' },
  'admin.dashboard.view_all': { id: 'Lihat Semua', en: 'View All' },
  'admin.dashboard.no_messages': { id: 'Tidak ada pesan baru', en: 'No new signals' },
  'admin.dashboard.talent_pipeline': { id: 'Pipeline Bakat', en: 'Talent Pipeline' },
  'admin.dashboard.no_apps': { id: 'Tidak ada lamaran terbaru', en: 'No recent applications' },
  'admin.dashboard.identity': { id: 'Identitas', en: 'Identity' },
  'admin.dashboard.media': { id: 'Media', en: 'Media' },
  'admin.dashboard.marketing': { id: 'Pemasaran', en: 'Marketing' },
  'admin.dashboard.stat.news': { id: 'Berita', en: 'News' },
  'admin.dashboard.stat.messages': { id: 'Pesan', en: 'Messages' },
  'admin.dashboard.stat.applications': { id: 'Lamaran', en: 'Applications' },
  'admin.dashboard.stat.active_jobs': { id: 'Lowongan Aktif', en: 'Active Jobs' },
  'admin.dashboard.stat.partners': { id: 'Mitra', en: 'Partners' },
  'admin.dashboard.stat.investor': { id: 'Investor', en: 'Investor' },
  'admin.dashboard.stat.branches': { id: 'Cabang Global', en: 'Global Branches' },
  'admin.dashboard.stat.certs': { id: 'Sertifikasi', en: 'Certifications' },
  'admin.dashboard.stat.news_desc': { id: 'Pembaruan diterbitkan', en: 'Published updates' },
  'admin.dashboard.stat.messages_desc': { id: 'Pesan belum dibaca', en: 'Unread inquiries' },
  'admin.dashboard.stat.applications_desc': { id: 'Menunggu ulasan', en: 'Pending review' },
  'admin.dashboard.stat.jobs_desc': { id: 'Posisi terbuka', en: 'Open positions' },
  'admin.dashboard.stat.partners_desc': { id: 'Jaringan bisnis', en: 'Business network' },
  'admin.dashboard.stat.investor_desc': { id: 'Laporan keuangan', en: 'Financial reports' },

  // Admin User Manager
  'admin.users.title': { id: 'Manajemen Pengguna', en: 'User Management' },
  'admin.users.subtitle': { id: 'Kelola akses administratif dan izin', en: 'Manage administrative access and permissions' },
  'admin.users.add': { id: 'Tambah Pengguna Baru', en: 'Add New User' },
  'admin.users.search_placeholder': { id: 'Cari nama atau email...', en: 'Search name or email...' },
  'admin.users.total_users': { id: 'Total: {count} Pengguna', en: 'Total: {count} Users' },
  'admin.users.table.identity': { id: 'Identitas Pengguna', en: 'User Identity' },
  'admin.users.table.role': { id: 'Peran Akses', en: 'Access Role' },
  'admin.users.table.registered': { id: 'Terdaftar', en: 'Registered' },
  'admin.users.table.control': { id: 'Kontrol', en: 'Control' },
  'admin.users.loading': { id: 'Sinkronisasi Database Pengguna...', en: 'Syncing User Database...' },
  'admin.users.empty': { id: 'Tidak ada pengguna yang cocok dengan pencarian Anda', en: 'No users found match your search' },
  'admin.users.modal.view_title': { id: 'Lihat Akses', en: 'View Access' },
  'admin.users.modal.edit_title': { id: 'Ubah Akses', en: 'Modify Access' },
  'admin.users.modal.create_title': { id: 'Buat Akses', en: 'Create Access' },
  'admin.users.modal.view_subtitle': { id: 'Melihat izin untuk pengguna administratif', en: 'Viewing permissions for administrative user' },
  'admin.users.modal.edit_subtitle': { id: 'Konfigurasi izin untuk pengguna administratif', en: 'Configure permissions for administrative user' },
  'admin.users.form.email': { id: 'Alamat Email', en: 'Email Address' },
  'admin.users.form.full_name': { id: 'Nama Lengkap', en: 'Full Name' },
  'admin.users.form.role': { id: 'Izin Sistem (Peran)', en: 'System Permissions (Role)' },
  'admin.users.form.role_viewer': { id: 'Viewer (Baca Saja)', en: 'Viewer (Read Only)' },
  'admin.users.form.role_editor': { id: 'Editor (Manajemen Konten)', en: 'Editor (Content Management)' },
  'admin.users.form.role_admin': { id: 'Admin (Manajemen Sistem)', en: 'Admin (System Management)' },
  'admin.users.form.role_super_admin': { id: 'Super Admin (Akses Penuh)', en: 'Super Admin (Full Access)' },
  'admin.users.form.granular_title': { id: 'Kontrol Akses Granular', en: 'Granular Access Control' },
  'admin.users.form.dynamic_rbac': { id: 'RBAC Dinamis', en: 'Dynamic RBAC' },
  'admin.users.form.access_enabled': { id: 'Akses Diaktifkan', en: 'Access Enabled' },
  'admin.users.form.no_access': { id: 'Tidak Ada Akses', en: 'No Access' },
  'admin.users.form.initial_password': { id: 'Kata Sandi Awal', en: 'Initial Password' },
  'admin.users.form.password_placeholder': { id: 'Minimal 6 karakter', en: 'Minimum 6 characters' },
  'admin.users.form.auth_warning': { id: 'Dengan menerbitkan pengguna ini, akun akan dibuat secara otomatis di sistem autentikasi dengan kata sandi yang diberikan.', en: 'By publishing this user, an account will be created automatically in the authentication system with the password provided.' },
  'admin.users.form.close': { id: 'Tutup', en: 'Close' },
  'admin.users.form.discard': { id: 'Buang', en: 'Discard' },
  'admin.users.form.save': { id: 'Simpan Perubahan', en: 'Save Changes' },
  'admin.users.form.publish': { id: 'Terbitkan Pengguna', en: 'Publish User' },

  // Admin Hero Manager
  'admin.hero.title': { id: 'Visual Hero', en: 'Hero Visuals' },
  'admin.hero.subtitle': { id: 'Kelola gambar banner dan video latar belakang berdampak tinggi', en: 'Manage banner images and high-impact background videos' },
  'admin.hero.add': { id: 'Buat Slide Baru', en: 'Create New Slide' },
  'admin.hero.search_placeholder': { id: 'Cari slide berdasarkan judul atau subjudul...', en: 'Search slides by title or subtitle...' },
  'admin.hero.loading': { id: 'Memuat aset visual...', en: 'Loading visual assets...' },
  'admin.hero.empty_title': { id: 'Tidak Ada Slide Ditemukan', en: 'No Slides Found' },
  'admin.hero.empty_desc': { id: 'Tidak ada slide yang cocok dengan kriteria pencarian Anda.', en: 'No slides match your search criteria.' },
  'admin.hero.add_first': { id: 'Tambah slide pertama sekarang', en: 'Add first slide now' },
  'admin.hero.table.order': { id: 'Urutan', en: 'Order' },
  'admin.hero.status.active': { id: 'Tampilan Aktif', en: 'Active Display' },
  'admin.hero.status.hidden': { id: 'Tersembunyi', en: 'Hidden' },
  'admin.hero.modal.edit_title': { id: 'Ubah Aset Visual', en: 'Modify Visual Asset' },
  'admin.hero.modal.create_title': { id: 'Buat Visual Baru', en: 'Create New Visual' },
  'admin.hero.modal.subtitle': { id: 'Tentukan pesan dan citra berdampak tinggi untuk bagian hero', en: 'Define high-impact messaging and imagery for the hero section' },
  'admin.hero.form.media_title': { id: 'Aset Media', en: 'Media Assets' },
  'admin.hero.form.bg_image': { id: 'Gambar Latar Belakang', en: 'Background Image' },
  'admin.hero.form.bg_video': { id: 'Video Latar Belakang (Opsional)', en: 'Background Video (Optional)' },
  'admin.hero.form.messaging_title': { id: 'Pesan Utama', en: 'Main Messaging' },
  'admin.hero.form.headline': { id: 'Headline', en: 'Headline' },
  'admin.hero.form.sub_headline': { id: 'Sub-headline', en: 'Sub-headline' },
  'admin.hero.form.cta_title': { id: 'Panggilan Aksi (CTA)', en: 'Call to Action (CTA)' },
  'admin.hero.form.primary_btn': { id: 'Tombol Utama', en: 'Primary Button' },
  'admin.hero.form.secondary_btn': { id: 'Tombol Sekunder', en: 'Secondary Button' },
  'admin.hero.form.label': { id: 'Label', en: 'Label' },
  'admin.hero.form.link': { id: 'Tautan (URL atau #anchor)', en: 'Link (URL or #anchor)' },
  'admin.hero.form.sort': { id: 'Urutan Sortir', en: 'Sort Order' },
  'admin.hero.form.visible': { id: 'Terlihat di Frontend', en: 'Visible on Frontend' },
  'admin.hero.form.update_btn': { id: 'Perbarui Visual', en: 'Update Visual' },
  'admin.hero.form.publish_btn': { id: 'Terbitkan Visual', en: 'Publish Visual' },

  // Admin Partner Manager
  'admin.partners.title': { id: 'Portofolio Mitra', en: 'Partner Portfolio' },
  'admin.partners.subtitle': { id: 'Kelola prinsipal perusahaan dan jaringan aliansi global', en: 'Manage company principals and global alliance networks' },
  'admin.partners.add': { id: 'Daftarkan Mitra', en: 'Register Partner' },
  'admin.partners.search_placeholder': { id: 'Cari mitra berdasarkan nama...', en: 'Search partners by name...' },
  'admin.partners.loading': { id: 'Sinkronisasi Protokol Aliansi...', en: 'Syncing Alliance Protocols...' },
  'admin.partners.empty_title': { id: 'Aliansi Kosong', en: 'Alliances Empty' },
  'admin.partners.empty_desc': { id: 'Belum ada mitra bisnis yang disinkronkan dengan grid.', en: 'No business partners have been synchronized with the grid.' },
  'admin.partners.add_first': { id: 'Tambahkan Aliansi Pertama', en: 'Anchor First Alliance' },
  'admin.partners.table.order': { id: 'Protokol #', en: 'Protocol #' },
  'admin.partners.status.active': { id: 'AKTIF', en: 'ACTIVE' },
  'admin.partners.status.offline': { id: 'OFFLINE', en: 'OFFLINE' },
  'admin.partners.modal.edit_title': { id: 'Ubah Aliansi', en: 'Modify Alliance' },
  'admin.partners.modal.create_title': { id: 'Daftarkan Mitra', en: 'Anchor Partner' },
  'admin.partners.modal.subtitle': { id: 'Terminal Konfigurasi Aliansi Strategis', en: 'Strategic Alliance Configuration Terminal' },
  'admin.partners.form.identity': { id: 'Identitas Mitra', en: 'Partner Identity' },
  'admin.partners.form.tier': { id: 'Tingkat Aliansi', en: 'Alliance Tier' },
  'admin.partners.form.assets': { id: 'Aset Sinyal (Logo)', en: 'Signal Assets (Logo)' },
  'admin.partners.form.uplink': { id: 'Uplink Eksternal (Situs Web)', en: 'External Uplink (Website)' },
  'admin.partners.form.priority': { id: 'Prioritas Urutan', en: 'Sort Priority' },
  'admin.partners.form.status': { id: 'Status Langsung', en: 'Live Status' },
  'admin.partners.form.narrative': { id: 'Narasi Strategis', en: 'Strategic Narrative' },
  'admin.partners.form.id_label': { id: 'ANALISIS INDONESIA', en: 'INDONESIAN ANALYSIS' },
  'admin.partners.form.en_label': { id: 'ANALISIS INGGRIS', en: 'ENGLISH ANALYSIS' },
  'admin.partners.form.update_btn': { id: 'KONFIRMASI PEMBARUAN', en: 'CONFIRM UPDATE' },
  'admin.partners.form.publish_btn': { id: 'BANGUN ALIANSI', en: 'ESTABLISH ALLIANCE' },
  'admin.partners.form.tier_principal': { id: 'Tingkat Prinsipal', en: 'Principal Tier' },
  'admin.partners.form.tier_international': { id: 'Tingkat Internasional', en: 'International Tier' },
  'admin.partners.form.anchor_asset': { id: 'Jangkarkan Aset Digital', en: 'Anchor Digital Asset' },

  // Admin Advantages Manager
  'admin.advantages.title': { id: 'Keunggulan Kompetitif', en: 'Competitive Advantages' },
  'admin.advantages.subtitle': { id: 'Kelola pembeda inti dan kekuatan perusahaan Anda', en: 'Manage your company\'s core differentiators and strengths' },
  'admin.advantages.add': { id: 'Keunggulan Baru', en: 'New Advantage' },
  'admin.advantages.loading': { id: 'Sinkronisasi Keunggulan...', en: 'Syncing Advantages...' },
  'admin.advantages.empty_title': { id: 'Tidak Ada Keunggulan Didefinisikan', en: 'No Advantages Defined' },
  'admin.advantages.add_first': { id: 'Tambah Keunggulan Pertama', en: 'Add First Advantage' },
  'admin.advantages.table.order': { id: 'Indeks Urutan #', en: 'Order Index #' },
  'admin.advantages.status.inactive': { id: 'Tidak Aktif', en: 'Inactive' },
  'admin.advantages.modal.title': { id: 'Detail Keunggulan', en: 'Advantage Details' },
  'admin.advantages.modal.subtitle': { id: 'Konfigurasi Pembeda Kompetitif', en: 'Configure Competitive Differentiator' },
  'admin.advantages.form.visual_symbol': { id: 'Pilih Simbol Visual', en: 'Select Visual Symbol' },
  'admin.advantages.form.manual_input': { id: 'Input Manual', en: 'Manual Input' },
  'admin.advantages.form.sort': { id: 'Urutan Sortir', en: 'Sort Order' },
  'admin.advantages.form.title_id': { id: 'Judul (ID)', en: 'Title (ID)' },
  'admin.advantages.form.title_en': { id: 'Judul (EN)', en: 'Title (EN)' },
  'admin.advantages.form.desc_id': { id: 'Deskripsi (ID)', en: 'Description (ID)' },
  'admin.advantages.form.desc_en': { id: 'Deskripsi (EN)', en: 'Description (EN)' },
  'admin.advantages.form.active': { id: 'Keunggulan Aktif', en: 'Active Advantage' },
  'admin.advantages.form.save': { id: 'Simpan Keunggulan', en: 'Save Advantage' },

  // Admin Business Line Manager
  'admin.business_lines.title': { id: 'Divisi Bisnis', en: 'Business Divisions' },
  'admin.business_lines.subtitle': { id: 'Kelola lini bisnis perusahaan dan divisi strategis global', en: 'Manage company business lines and global strategic divisions' },
  'admin.business_lines.add': { id: 'Tambah Divisi', en: 'Add Division' },
  'admin.business_lines.search_placeholder': { id: 'Cari divisi berdasarkan judul atau slug...', en: 'Search divisions by title or slug...' },
  'admin.business_lines.loading': { id: 'Menyinkronkan Unit Global...', en: 'Synchronizing Global Units...' },
  'admin.business_lines.empty_title': { id: 'Arsitektur Kosong', en: 'Architecture Empty' },
  'admin.business_lines.empty_desc': { id: 'Tidak ada divisi bisnis yang ditemukan sesuai pencarian Anda.', en: 'No business divisions found matching your search.' },
  'admin.business_lines.add_first': { id: 'Deploy Strategi Baru', en: 'Deploy New Strategy' },
  'admin.business_lines.table.gallery': { id: 'GALERI', en: 'GALLERY' },
  'admin.business_lines.table.order': { id: 'Protokol Urutan #', en: 'Sequence Protocol #' },
  'admin.business_lines.status.active': { id: 'AKTIF', en: 'ACTIVE' },
  'admin.business_lines.status.inactive': { id: 'NONAKTIF', en: 'DEACTIVATED' },
  'admin.business_lines.modal.edit_title': { id: 'Konfigurasi Unit', en: 'Configure Unit' },
  'admin.business_lines.modal.create_title': { id: 'Deploy Divisi', en: 'Deploy Division' },
  'admin.business_lines.modal.subtitle': { id: 'Terminal Kontrol Arsitektur Bisnis', en: 'Business Architecture Control Terminal' },
  'admin.business_lines.form.title_id': { id: 'Judul Divisi (ID)', en: 'Division Title (ID)' },
  'admin.business_lines.form.title_en': { id: 'Judul Divisi (EN)', en: 'Division Title (EN)' },
  'admin.business_lines.form.slug': { id: 'Slug Global / ID', en: 'Global Slug / ID' },
  'admin.business_lines.form.sort': { id: 'Urutan Sekuens', en: 'Sequence Order' },
  'admin.business_lines.form.status': { id: 'Status', en: 'Status' },
  'admin.business_lines.form.status_active': { id: 'LIVE & GLOBAL', en: 'LIVE & GLOBAL' },
  'admin.business_lines.form.status_inactive': { id: 'DRAF SEKUEN', en: 'DRAFT SEQUENCE' },
  'admin.business_lines.form.subtitle_id': { id: 'Subjudul (ID)', en: 'Subtitle (ID)' },
  'admin.business_lines.form.subtitle_en': { id: 'Subjudul (EN)', en: 'Subtitle (EN)' },
  'admin.business_lines.form.color': { id: 'Tema Warna (Aksen)', en: 'Color Theme (Accent)' },
  'admin.business_lines.form.icon': { id: 'Jenis Ikon', en: 'Icon Type' },
  'admin.business_lines.form.features_title': { id: 'Fitur Divisi (Kapabilitas)', en: 'Divisional Features (Capabilities)' },
  'admin.business_lines.form.features_add': { id: 'Tambah Kapabilitas', en: 'Add Capability' },
  'admin.business_lines.form.features_empty': { id: 'Belum ada kapabilitas yang ditentukan untuk sekuen ini', en: 'No capabilities defined for this sequence' },
  'admin.business_lines.form.visual_title': { id: 'Aset Visualisasi Divisi', en: 'Division Visualization Assets' },
  'admin.business_lines.form.visual_add': { id: 'Tambah Aset Visual', en: 'Add Visual Asset' },
  'admin.business_lines.form.visual_primary': { id: 'Inti Utama', en: 'Primary Core' },
  'admin.business_lines.form.visual_info': { id: 'Informasi Sekuen: Aset \'Inti Utama\' akan berfungsi sebagai thumbnail identitas global.', en: 'Sequence Information: The \'Primary Core\' asset will serve as the global identity thumbnail.' },
  'admin.business_lines.form.analysis_title': { id: 'Analisis Strategis & Ringkasan', en: 'Strategic Analysis & Summary' },
  'admin.business_lines.form.id_label': { id: 'NARASI INDONESIA', en: 'INDONESIAN NARRATIVE' },
  'admin.business_lines.form.en_label': { id: 'NARASI INGGRIS', en: 'ENGLISH NARRATIVE' },
  'admin.business_lines.form.confirm_btn': { id: 'Konfirmasi Konfigurasi', en: 'Confirm Configuration' },

  // Admin Certification Manager
  'admin.certifications.title': { id: 'Kualitas & Sertifikasi', en: 'Quality & Certifications' },
  'admin.certifications.subtitle': { id: 'Kelola standar ISO global dan kredensial kepemimpinan industri', en: 'Manage global ISO standards and industry leadership credentials' },
  'admin.certifications.add': { id: 'Tambah Sertifikat', en: 'Add Certificate' },
  'admin.certifications.search_placeholder': { id: 'Cari sertifikasi berdasarkan nama, penerbit, atau nomor...', en: 'Search certifications by name, issuer, or number...' },
  'admin.certifications.loading': { id: 'Memindai Buku Besar Kualitas...', en: 'Scanning Quality Ledger...' },
  'admin.certifications.empty_title': { id: 'Kredensial Tidak Ditemukan', en: 'No Credentials Found' },
  'admin.certifications.empty_desc': { id: 'Tidak ada sertifikasi yang cocok dengan kriteria pencarian Anda.', en: 'No certifications match your search criteria.' },
  'admin.certifications.add_first': { id: 'Verifikasi Entri Global', en: 'Verify Global Entry' },
  'admin.certifications.status.valid': { id: 'VALID', en: 'VALID' },
  'admin.certifications.status.expired': { id: 'KADALUWARSA', en: 'EXPIRED' },
  'admin.certifications.registry_code': { id: 'Kode Registri', en: 'Registry Code' },
  'admin.certifications.modal.edit_title': { id: 'Kalibrasi Lencana', en: 'Calibrate Badge' },
  'admin.certifications.modal.create_title': { id: 'Jangkarkan Kredensial', en: 'Anchor Credential' },
  'admin.certifications.modal.subtitle': { id: 'Sistem Penyelarasan Standar Kualitas', en: 'Quality Standard Alignment System' },
  'admin.certifications.form.name': { id: 'Nama Kredensial Resmi', en: 'Official Credential Name' },
  'admin.certifications.form.issuer': { id: 'Otoritas / Penerbit', en: 'Authority / Issuer' },
  'admin.certifications.form.number': { id: 'Nomor Registri', en: 'Registry Number' },
  'admin.certifications.form.asset': { id: 'Jangkarkan Aset Terpindai', en: 'Anchor Scanned Asset' },
  'admin.certifications.form.status': { id: 'Status Langsung', en: 'Live Status' },
  'admin.certifications.form.status_active': { id: 'Terverifikasi & Aktif', en: 'Verified & Active' },
  'admin.certifications.form.status_inactive': { id: 'Diprioritaskan / Kadaluwarsa', en: 'Deprioritized / Expired' },
  'admin.certifications.form.narrative_title': { id: 'Narasi Teknis & Dampak', en: 'Technical Narrative & Impact' },
  'admin.certifications.form.id_label': { id: 'NARASI INDONESIA', en: 'INDONESIAN NARRATIVE' },
  'admin.certifications.form.en_label': { id: 'NARASI INGGRIS', en: 'ENGLISH NARRATIVE' },
  'admin.certifications.form.update_btn': { id: 'PERBARUI KREDENSIAL', en: 'UPDATE CREDENTIAL' },
  'admin.certifications.form.publish_btn': { id: 'JANGKARKAN POSISI', en: 'ANCHOR POSITION' },

  // Admin Branch Manager
  'admin.branch.title': { id: 'Jaringan Cabang', en: 'Branch Network' },
  'admin.branch.subtitle': { id: 'Kelola lokasi fisik, kantor pusat, dan titik distribusi', en: 'Manage physical locations, headquarters, and distribution points' },
  'admin.branch.add': { id: 'Tambah Node', en: 'Add Node' },
  'admin.branch.search_placeholder': { id: 'Cari node berdasarkan nama, kota, atau provinsi...', en: 'Search nodes by name, city, or province...' },
  'admin.branch.stats.nodes': { id: 'TOTAL NODE FISIK', en: 'TOTAL PHYSICAL NODES' },
  'admin.branch.stats.hq': { id: 'KANTOR PUSAT', en: 'HEADQUARTERS' },
  'admin.branch.stats.active': { id: 'CABANG AKTIF', en: 'ACTIVE BRANCHES' },
  'admin.branch.stats.depots': { id: 'DEPO LOGISTIK', en: 'LOGISTICS DEPOTS' },
  'admin.branch.stats.distribution_points': { id: 'TITIK DISTRIBUSI', en: 'DISTRIBUTION POINTS' },
  'admin.branch.filter.universal': { id: 'UNIVERSAL', en: 'UNIVERSAL' },
  'admin.branch.filter.hq': { id: 'KANTOR PUSAT', en: 'HEADQUARTERS' },
  'admin.branch.filter.branches': { id: 'CABANG', en: 'BRANCHES' },
  'admin.branch.filter.depots': { id: 'DEPO', en: 'DEPOTS' },
  'admin.branch.table.sequence': { id: 'URUTAN JARINGAN', en: 'NETWORK SEQUENCE' },
  'admin.branch.table.identity': { id: 'IDENTITAS NODE', en: 'NODE IDENTITY' },
  'admin.branch.table.type': { id: 'TIPE STRUKTUR', en: 'STRUCTURE TYPE' },
  'admin.branch.table.position': { id: 'POSISI GEOSPASIAL', en: 'GEOSPATIAL POSITION' },
  'admin.branch.table.status': { id: 'STATUS OPERASIONAL', en: 'OPERATIONAL STATUS' },
  'admin.branch.table.actions': { id: 'KONTROL', en: 'CONTROLS' },
  'admin.branch.loading': { id: 'Sinkronisasi Topologi Jaringan...', en: 'Syncing Network Topology...' },
  'admin.branch.empty': { id: 'Grid Jaringan Kosong', en: 'Network Grid Empty' },
  'admin.branch.status.active': { id: 'AKTIF', en: 'ACTIVE' },
  'admin.branch.status.inactive': { id: 'SIAGA', en: 'STANDBY' },
  'admin.branch.modal.add': { id: 'Membangun Node Baru', en: 'Construct New Node' },
  'admin.branch.modal.edit': { id: 'Konfigurasi Ulang Node', en: 'Reconfigure Node' },
  'admin.branch.modal.terminal': { id: 'Terminal Manajemen Lokasi Fisik', en: 'Physical Location Management Terminal' },
  'admin.branch.form.name': { id: 'Penanda Node (Nama)', en: 'Node Designator (Name)' },
  'admin.branch.form.type': { id: 'Klasifikasi Struktural', en: 'Structural Classification' },
  'admin.branch.form.city': { id: 'Sektor Kota', en: 'City Sector' },
  'admin.branch.form.province': { id: 'Wilayah Provinsi', en: 'Province Region' },
  'admin.branch.form.address': { id: 'Koordinat Alamat Lengkap', en: 'Exact Address Coordinates' },
  'admin.branch.form.phone': { id: 'Saluran Komunikasi (Telepon)', en: 'Comm Line (Phone)' },
  'admin.branch.form.email': { id: 'Uplink Digital (Email)', en: 'Digital Uplink (Email)' },
  'admin.branch.form.geo': { id: 'DATA GEOLOKASI', en: 'GEOLOCATION DATA' },
  'admin.branch.form.coords_extracted': { id: 'KOORDINAT DIEKSTRAKSI', en: 'COORDS EXTRACTED' },
  'admin.branch.form.map_link': { id: 'Tautan Google Maps', en: 'Google Maps Link' },
  'admin.branch.form.lat': { id: 'GARIS LINTANG', en: 'LATITUDE' },
  'admin.branch.form.lng': { id: 'GARIS BUJUR', en: 'LONGITUDE' },
  'admin.branch.form.status': { id: 'Status Operasional', en: 'Operational Status' },
  'admin.branch.form.active_desc': { id: 'Node Sepenuhnya Operasional', en: 'Node Fully Operational' },
  'admin.branch.form.standby_desc': { id: 'Node Offline / Pemeliharaan', en: 'Node Offline / Maintenance' },
  'admin.branch.form.discard': { id: 'Batalkan Konstruksi', en: 'Abort Construction' },
  'admin.branch.form.deploy_btn': { id: 'DEPLOY NODE', en: 'DEPLOY NODE' },
  'admin.branch.form.update_btn': { id: 'PERBARUI KONFIGURASI', en: 'UPDATE CONFIG' },

  // Common Admin Actions Extended
  'common.export': { id: 'Ekspor', en: 'Export' },
  'common.per_page': { id: 'per halaman', en: 'per page' },
  'common.showing': { id: 'Menampilkan', en: 'Showing' },
  'common.of': { id: 'dari', en: 'of' },
  'common.active': { id: 'Aktif', en: 'Active' },
  'common.inactive': { id: 'Tidak Aktif', en: 'Inactive' },
  'common.draft_label': { id: 'Draf', en: 'Draft' },

  // Common Admin Actions
  'common.search': { id: 'Cari...', en: 'Search...' },
  'common.loading': { id: 'Memuat...', en: 'Loading...' },
  'common.save': { id: 'Simpan', en: 'Save' },
  'common.cancel': { id: 'Batal', en: 'Cancel' },
  'common.delete': { id: 'Hapus', en: 'Delete' },
  'common.edit': { id: 'Ubah', en: 'Edit' },
  'common.view': { id: 'Lihat', en: 'View' },
  'common.add': { id: 'Tambah', en: 'Add' },
  'common.actions': { id: 'Aksi', en: 'Actions' },
  'common.status': { id: 'Status', en: 'Status' },
  'common.date': { id: 'Tanggal', en: 'Date' },
  'common.category': { id: 'Kategori', en: 'Category' },
  'common.title': { id: 'Judul', en: 'Title' },
  'common.description': { id: 'Deskripsi', en: 'Description' },
  'common.content': { id: 'Konten', en: 'Content' },
  'common.image': { id: 'Gambar', en: 'Image' },
  'common.publish': { id: 'Publikasikan', en: 'Publish' },
  'common.draft': { id: 'Draf', en: 'Draft' },
  'common.close': { id: 'Tutup', en: 'Close' },
  'common.discard': { id: 'Buang', en: 'Discard' },
  'common.sync': { id: 'Sinkronisasi', en: 'Sync' },
  'common.auto_translate': { id: 'Terjemahan Otomatis', en: 'Auto Translate' },
  'common.read_only_mode': { id: 'Mode Baca-Saja', en: 'Read-Only Mode' },
  'common.read_only_warning': { id: 'Anda sedang melihat data ini dalam mode pratinjau. Perubahan tidak dapat disimpan.', en: 'You are viewing this data in preview mode. Changes cannot be saved.' },

  'admin.dashboard.welcome': { id: 'Selamat Datang di Admin', en: 'Welcome to Admin' },
  'admin.dashboard.subtitle': { id: 'Kelola identitas korporat, berita, karir, dan operasi bisnis Anda dari pusat komando.', en: 'Manage your corporate identity, news, careers, and global business operations from one central command.' },
  'admin.dashboard.system_overview': { id: 'Ihtisar Sistem', en: 'System Overview' },
  'admin.dashboard.stat.branches': { id: 'Cabang', en: 'Branches' },
  'admin.dashboard.stat.certs': { id: 'Sertifikat', en: 'Certificates' },
  'admin.dashboard.stat.news': { id: 'Berita', en: 'News Articles' },
  'admin.dashboard.stat.messages': { id: 'Pesan Baru', en: 'New Messages' },
  'admin.dashboard.stat.applications': { id: 'Lamaran Pekerjaan', en: 'Job Apps' },
  'admin.dashboard.stat.active_jobs': { id: 'Lowongan Aktif', en: 'Active Jobs' },
  'admin.dashboard.stat.partners': { id: 'Mitra', en: 'Partners' },
  'admin.dashboard.stat.investor': { id: 'Dokumen Investor', en: 'Investor Docs' },
  'admin.dashboard.recent_messages': { id: 'Pesan Masuk Terbaru', en: 'Recent Inquiries' },
  'admin.dashboard.talent_pipeline': { id: 'Saluran Bakat', en: 'Talent Pipeline' },
  'admin.dashboard.view_all': { id: 'Lihat Semua', en: 'View All' },
  'admin.dashboard.no_messages': { id: 'Tidak Ada Pesan Terbaru', en: 'No Recent Messages' },
  'admin.dashboard.no_apps': { id: 'Tidak Ada Lamaran Baru', en: 'No Recent Applications' },
  'admin.dashboard.quick_links': { id: 'Tautan Cepat', en: 'Quick Links' },
  'admin.dashboard.media': { id: 'Media', en: 'Media' },
  'admin.dashboard.identity': { id: 'Identitas', en: 'Identity' },
  'admin.dashboard.marketing': { id: 'Pemasaran', en: 'Marketing' },

  'admin.company.title': { id: 'Profil', en: 'Profile' },
  'admin.company.subtitle': { id: 'Kelola identitas inti Penta Valent', en: 'Manage the core identity of Penta Valent' },
  'admin.company.tabs.general': { id: 'Info Umum', en: 'General Info' },
  'admin.company.tabs.structure': { id: 'Struktur', en: 'Structure' },
  'admin.company.tabs.management': { id: 'Manajemen', en: 'Management' },
  'admin.company.tabs.history': { id: 'Sejarah', en: 'History' },
  'admin.company.tabs.values': { id: 'Nilai-Nilai', en: 'Values' },
  'admin.company.tabs.advantages': { id: 'Keunggulan', en: 'Advantages' },
  'admin.company.tabs.services': { id: 'Lini Bisnis', en: 'Business Lines' },
  'admin.company.tabs.quality': { id: 'Kualitas', en: 'Quality' },
  'admin.company.tabs.partners': { id: 'Mitra', en: 'Partners' },
  'admin.company.tabs.branches': { id: 'Cabang', en: 'Branches' },
  'admin.company.tabs.legal': { id: 'Dokumen Hukum', en: 'Legal Documents' },

  'admin.company.general.title': { id: 'PENGATURAN PROFIL UMUM', en: 'GENERAL PROFILE SETTINGS' },
  'admin.company.general.subtitle': { id: 'Kelola narasi inti, visi, misi, dan metrik utama', en: 'Manage your core narrative, vision, mission, and key metrics' },
  'admin.company.general.apply': { id: 'TERAPKAN PERUBAHAN', en: 'APPLY CHANGES' },
  'admin.company.general.tab.profile': { id: 'Profil Perusahaan', en: 'Company Profile' },
  'admin.company.general.tab.member': { id: 'Data Anggota', en: 'Member Data' },
  'admin.company.general.tab.visual': { id: 'Struktur Visual', en: 'Visual Structure' },

  'admin.news.title': { id: 'Berita & Media', en: 'News & Media' },
  'admin.news.subtitle': { id: 'Kelola artikel berita dan siaran pers', en: 'Manage news articles and press releases' },
  'admin.news.add': { id: 'Tambah Berita', en: 'Add News' },
  'admin.news.table.title': { id: 'Judul', en: 'Title' },
  'admin.news.table.category': { id: 'Kategori', en: 'Category' },
  'admin.news.table.status': { id: 'Status', en: 'Status' },
  'admin.news.table.date': { id: 'Tanggal', en: 'Date' },
  'admin.news.table.actions': { id: 'Aksi', en: 'Actions' },
  'admin.news.form.update_title': { id: 'Perbarui Artikel', en: 'Update Article' },
  'admin.news.form.draft_title': { id: 'Draf Artikel Baru', en: 'Draft New Article' },
  'admin.news.form.console': { id: 'Konsol Berita & Media Global', en: 'Global News & Media Console' },
  'admin.news.form.title_id': { id: 'Judul (Bahasa Indonesia)', en: 'Title (Bahasa Indonesia)' },
  'admin.news.form.title_en': { id: 'Judul (English)', en: 'Title (English)' },
  'admin.news.form.slug': { id: 'Slug (URL Mapping)', en: 'Slug (URL Mapping)' },
  'admin.news.form.category': { id: 'Kategori Artikel', en: 'Article Category' },
  'admin.news.form.gallery_title': { id: 'Galeri Sinematik', en: 'Cinematic Gallery' },
  'admin.news.form.gallery_subtitle': { id: 'Gambar slider artikel utama', en: 'Main article slider images' },
  'admin.news.form.summary_id': { id: 'Ringkasan (ID)', en: 'Summary (ID)' },
  'admin.news.form.summary_en': { id: 'Ringkasan (EN)', en: 'Summary (EN)' },
  'admin.news.form.content_id': { id: 'Konten Lengkap (ID)', en: 'Full Article Content (ID)' },
  'admin.news.form.content_en': { id: 'Konten Lengkap (EN)', en: 'Full Article Content (EN)' },
  'admin.news.form.visibility': { id: 'Visibilitas Publik', en: 'Public Visibility' },
  'admin.news.form.live': { id: 'Tayang di Produksi', en: 'Live on Production' },
  'admin.news.form.private': { id: 'Disimpan di Draf Pribadi', en: 'Saved in Private Drafts' },
  'admin.news.form.launch': { id: 'Luncurkan Artikel Baru', en: 'Launch New Article' },
  'admin.news.form.update_btn': { id: 'Perbarui Artikel Global', en: 'Update Global Article' },
  'admin.news.form.auto_translate': { id: 'Terjemahan Otomatis', en: 'Auto Translate' },
  'admin.news.form.sync': { id: 'Sinkronisasi', en: 'Sync' },
  'admin.news.form.add_slide': { id: 'Tambah Slide', en: 'Add Slide' },
  'admin.news.form.no_visuals': { id: 'Tidak Ada Gambar Terlampir', en: 'No Visuals Attached' },
  'admin.news.form.discard': { id: 'Buang Perubahan', en: 'Discard Changes' },
  'admin.news.form.close_preview': { id: 'Tutup Pratinjau', en: 'Close Preview' },
  'admin.news.form.published': { id: 'Diterbitkan', en: 'Published' },
  'admin.news.form.draft': { id: 'Draf', en: 'Draft' },
  'admin.news.form.no_matches': { id: 'Tidak ada hasil yang cocok', en: 'No matches found' },
  'admin.news.form.no_articles': { id: 'Belum ada artikel berita', en: 'No news articles yet' },
  'admin.news.form.showing': { id: 'Menampilkan', en: 'Showing' },
  'admin.news.form.of': { id: 'dari', en: 'of' },
  'admin.news.form.per_page': { id: 'per halaman', en: 'per page' },
  'admin.news.form.comments_title': { id: 'Diskusi Publik', en: 'Public Discussion' },
  'admin.news.form.no_comments': { id: 'Belum Ada Masukan Komunitas', en: 'No Community Input Yet' },
  'admin.news.form.official_reply': { id: 'Balasan Resmi', en: 'Official Reply' },
  'admin.news.form.reply_placeholder': { id: 'Ketik tanggapan resmi Anda...', en: 'Type your official response...' },
  'admin.news.form.enterprise_support': { id: 'Dukungan Perusahaan', en: 'Enterprise Support' },
  'admin.news.form.approved': { id: 'Disetujui', en: 'Approved' },
  'admin.news.form.hidden': { id: 'Disembunyikan', en: 'Hidden' },
  'admin.news.form.scanning': { id: 'Memindai Diskusi...', en: 'Scanning Discussions...' },
  'admin.news.form.confirm_launch_title': { id: 'Luncurkan Artikel', en: 'Launch Article' },
  'admin.news.form.confirm_launch_msg': { id: 'Anda akan menerbitkan artikel ini ke jaringan media global. Lanjutkan?', en: 'You are about to publish this piece to the global media network. Proceed?' },
  'admin.news.form.confirm_update_title': { id: 'Paksa Perbarui', en: 'Force Update' },
  'admin.news.form.confirm_update_msg': { id: 'Apakah Anda yakin ingin menerapkan perubahan ini ke produksi?', en: 'Are you sure you want to deploy these changes to production?' },
  'admin.news.form.confirm_deploy_btn': { id: 'Luncurkan Sekarang', en: 'Deploy Now' },
  'admin.news.form.confirm_push_btn': { id: 'Push Perubahan', en: 'Push Changes' },

  'admin.investor.title': { id: 'Hubungan Investor', en: 'Investor Relations' },
  'admin.investor.subtitle': { id: 'Kelola Dokumen, Rasio, dan Data Pemegang Saham', en: 'Manage Documents, Ratios, and Shareholder Data' },
  'admin.investor.tabs.documents': { id: 'Dokumen', en: 'Documents' },
  'admin.investor.tabs.highlights': { id: 'Sorotan', en: 'Highlights' },
  'admin.investor.tabs.ratios': { id: 'Rasio Keuangan', en: 'Fin. Ratios' },
  'admin.investor.tabs.shareholders': { id: 'Pemegang Saham', en: 'Shareholders' },
  'admin.investor.tabs.dividends': { id: 'Dividen', en: 'Dividends' },
  'admin.investor.tabs.calendar': { id: 'Kalender', en: 'Calendar' },
  'admin.investor.form.add_new': { id: 'Tambah Item Baru', en: 'Add New Item' },
  'admin.investor.form.upload_doc': { id: 'Unggah Dokumen', en: 'Upload Document' },
  'admin.investor.form.search_docs': { id: 'Cari dokumen...', en: 'Search documents...' },
  'admin.investor.form.edit_item': { id: 'Ubah Item', en: 'Edit Item' },
  'admin.investor.form.create_item': { id: 'Buat Item Baru', en: 'Create New Item' },
  'admin.investor.form.title_id': { id: 'Judul (ID)', en: 'Title (ID)' },
  'admin.investor.form.title_en': { id: 'Judul (EN)', en: 'Title (EN)' },
  'admin.investor.form.type': { id: 'Tipe', en: 'Type' },
  'admin.investor.form.year': { id: 'Tahun', en: 'Year' },
  'admin.investor.form.pdf': { id: 'Dokumen PDF', en: 'PDF Document' },
  'admin.investor.form.label_id': { id: 'Label (ID)', en: 'Label (ID)' },
  'admin.investor.form.label_en': { id: 'Label (EN)', en: 'Label (EN)' },
  'admin.investor.form.value': { id: 'Nilai', en: 'Value' },
  'admin.investor.form.growth': { id: 'Pertumbuhan', en: 'Growth' },
  'admin.investor.form.icon': { id: 'Ikon', en: 'Icon' },
  'admin.investor.form.desc_id': { id: 'Deskripsi (ID)', en: 'Desc (ID)' },
  'admin.investor.form.desc_en': { id: 'Deskripsi (EN)', en: 'Desc (EN)' },
  'admin.investor.form.sh_name': { id: 'Nama Pemegang Saham', en: 'Shareholder Name' },
  'admin.investor.form.percentage': { id: 'Persentase (%)', en: 'Percentage (%)' },
  'admin.investor.form.color_start': { id: 'Warna Mulai (Tailwind)', en: 'Color Start (Tailwind)' },
  'admin.investor.form.color_end': { id: 'Warna Akhir (Tailwind)', en: 'Color End (Tailwind)' },
  'admin.investor.form.amount': { id: 'Jumlah (misal: 15 IDR/Saham)', en: 'Amount (e.g. 15 IDR/Share)' },
  'admin.investor.form.event_date': { id: 'Tanggal Acara', en: 'Event Date' },
  'admin.investor.form.event_type': { id: 'Tipe Acara', en: 'Event Type' },
  'admin.investor.form.publish_cal': { id: 'Terbitkan ke Kalender', en: 'Publish to Calendar' },
  'admin.investor.form.save': { id: 'Simpan Perubahan', en: 'Save Changes' },
  'admin.investor.form.period': { id: 'Periode', en: 'Period' },
  'admin.investor.form.hidden': { id: 'Tersembunyi', en: 'Hidden' },

  'admin.messages.title': { id: 'Pesan Kontak', en: 'Contact Messages' },
  'admin.messages.subtitle_unread': { id: '{count} pesan belum dibaca', en: '{count} unread message(s)' },
  'admin.messages.subtitle_all_read': { id: 'Semua pesan sudah dibaca', en: 'All messages read' },
  'admin.messages.filter.all': { id: 'Semua', en: 'All' },
  'admin.messages.filter.unread': { id: 'Belum Dibaca', en: 'Unread' },
  'admin.messages.filter.read': { id: 'Sudah Dibaca', en: 'Read' },
  'admin.messages.empty': { id: 'Tidak ada pesan', en: 'No messages' },
  'admin.messages.select_prompt': { id: 'Pilih pesan untuk melihat detail', en: 'Select a message to view details' },

  'admin.careers.title': { id: 'Manajemen Karir', en: 'Career Management' },
  'admin.careers.subtitle': { id: 'Kelola lowongan pekerjaan dan deskripsi', en: 'Manage job openings and descriptions' },
  'admin.careers.add': { id: 'Tambah Lowongan', en: 'Add Opening' },

  'admin.applications.title': { id: 'Lamaran Pekerjaan', en: 'Job Applications' },
  'admin.applications.subtitle': { id: 'Tinjau dan kelola lamaran masuk', en: 'Review and manage incoming applications' },
  'admin.applications.table.candidate': { id: 'Kandidat', en: 'Candidate' },
  'admin.applications.table.position': { id: 'Posisi', en: 'Position' },
  'admin.applications.table.applied_at': { id: 'Melamar Pada', en: 'Applied At' },

  // Public Page Updates (Step 1837)
  'mgmt.title': { id: 'Kepemimpinan Eksekutif', en: 'Executive Leadership' },
  'mgmt.visionary': { id: 'Visioner', en: 'Visionary' },
  'mgmt.governance': { id: 'Tata Kelola', en: 'Governance' },
  'mgmt.desc': { id: 'Keunggulan strategis dan operasional kami dipandu oleh tim veteran industri yang beragam, berdedikasi pada pertumbuhan berkelanjutan dan inovasi kesehatan.', en: 'Our strategic and operational excellence is guided by a diverse team of industry veterans dedicated to sustainable growth and healthcare innovation.' },

  'stats.market_reach': { id: 'Jangkauan Pasar', en: 'Market Reach' },

  'network.header.title': { id: 'Jaringan Distribusi Nasional', en: 'National Distribution Network' },
  'network.header.subtitle': { id: 'Jaringan Penta Valent', en: 'Penta Valent Network' },
  'network.header.desc': { id: 'Menjangkau seluruh pelosok Indonesia dengan infrastruktur logistik modern dan terintegrasi untuk memastikan ketersediaan produk kesehatan yang merata & tepat waktu.', en: 'Reaching every corner of Indonesia with modern and integrated logistics infrastructure to ensure equitable & timely availability of healthcare products.' },

  'map.header': { id: 'Lokasi Kami', en: 'Our Locations' },
  'map.subHeader': { id: 'Temukan cabang dan depo terdekat di kota Anda', en: 'Find the nearest branch and depot in your city' },

  'qa.title': { id: 'Jaminan Kualitas', en: 'Quality Assurance' },
  'qa.subtitle': { id: 'Standar Tak Terkompromi', en: 'Uncompromising Standards' },
  'qa.desc': { id: 'Penta Valent mematuhi kerangka regulasi global dan nasional tertinggi untuk memastikan keamanan dan efikasi setiap produk dalam rantai pasok kami.', en: 'Penta Valent adheres to the highest global and national regulatory frameworks to ensure every product\'s safety and efficacy within our supply chain.' },
  'qa.cdob.title': { id: 'Bersertifikat CDOB (GDP)', en: 'CDOB Certified (GDP)' },
  'qa.cdob.desc': { id: 'Sertifikasi nasional untuk standar distribusi farmasi.', en: 'National certification for pharmaceutical distribution standards.' },
  'qa.iso.title': { id: 'Kepatuhan ISO 9001:2015', en: 'ISO 9001:2015 Compliant' },
  'qa.iso.desc': { id: 'Sertifikasi manajemen mutu internasional.', en: 'International quality management certification.' },

  'gcg.tagline': { id: 'TATA KELOLA PERUSAHAAN', en: 'CORPORATE GOVERNANCE' },
  'gcg.title.text': { id: 'Tata Kelola,', en: 'Good Corporate,' },
  'gcg.title.italic': { id: 'Perusahaan yang Baik', en: 'Governance Excellence' },
  'gcg.description': { id: 'Penta Valent berkomitmen untuk menjunjung tinggi standar transparansi, akuntabilitas, dan integritas dalam seluruh aspek operasional bisnis kami.', en: 'Penta Valent is committed to upholding the highest standards of transparency, accountability, and integrity across all aspects of our business operations.' },

  'career.future.title': { id: 'Future Talent Pipeline', en: 'Future Talent Pipeline' },
  'career.future.desc': { id: 'Bangun Masa Depan Kesehatan Bersama Kami', en: 'Build the Future of Healthcare With Us' },

  'contact.cta.title': { id: 'Hubungkan Visi Anda', en: 'Connect Your Vision' },
  'contact.cta.subtitle': { id: 'Saluran Intelijen Langsung', en: 'Direct Intelligence Channel' },
  'contact.fast_response': { id: 'Jalur Respon Cepat', en: 'Fast Response Line' },
  'map.view_on_map': { id: 'Lihat Detail Lokasi', en: 'Explore Location Details' },

};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('peve-language');
    return (saved as Language) || 'id';
  });

  useEffect(() => {
    localStorage.setItem('peve-language', language);
  }, [language]);

  const t = (key: string): string => {
    const translation = translations[key];
    if (!translation) return key;
    return translation[language] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
